;; from http://www.heartwoodguitar.com/strum-pattern/
;; "1 + 2 + 3 + 4 + "
;; "B   D U B   D U "
(def patterns44
  ["B   D U B   D U "
   "D d D d D d D DU"
   "D   D U D   D U "
   "D   D U   U D U "
   "B   D DUB   D DU"
   "B   D U B U D U "
   "D B D B D B D B "
   "D D D D D D D DU"
   "    D D     D   "
   "D D D D D D D D "
   "D   D  UD D  UDU"
   "D   D DUM D M D "
   "    D DUM D M D "
   "D B D DUD B D DU"
   "D d D DUD d D DU"
   "D   D U D   D U " 
   "D   D U D U D U "
   "D   D U   U D U "
   "B   D U   U D U "
   "D   D U   U D UD"  
   "U   D U   U D UD"
   "D   D  UD D  UDU"  
   "D   D  UDUD  UDU"
   "D   D     U D U "  
   "  U D     U D U "
   "D B D DU UD  UDU"
   "D U X X D U X X "
   "D D             "
   "D D D D D D D D "
   "B B D DUB B D DU"
   "D d D d D d D d "
   "D     U D U D   "
   "  U D U D U D U "
   "D D D D D D D DU"
   "D     D         "  
   "D D   D         "
   "B   D   D U D U "
   "D D D D D D D D "
   "D   B   D   D U "
   "D   D U   U D   "  
   "D U   U D U D U "
   "D  UD D  UD DUDU"
   "D   D DUD   D DU"
   "D U   U D U D U "  
   "D U   U D   D DU"
   "D           D DU"
   "D               "  
   "M D D D D D D DU"
   "D     DUD     DU"
   "D   D U   U X U "
   "D D D DU U UDUDU"
   "D  U UD  U UDUDU"
   "D   D DU UD D DU"
   "D DU UD DU UDUDU"
   "B   D U D U D U "  
   "  U D U D U D U "
   "D D X DUD D X DU"
   "D DUD DUD DUD DU"
   "B B D DUB B D DU"
   "B   D U B   D U "
   "D U X U D U X U "
   "B B D D B B D D "
   "D   X U D   X U "
   "B   D U   U D U "
   "B   D DU UB DU U"
   "B   D     U D U "  
   "D   D U D   D U "
   "D U X U   U D U "
   "D   D   D U D U "
   "D   D   D U D U "
   "D   D U D   D U "  
   "  U D   D U D U "
   "D   M U         "
   "D     U         "
   "D   D U D   D   "
   "D U   U   U   U "  
   "  U   U   U   U "
   "D DU UD DU UDUDU"  
   "D DUDU U U U UDU"
   "D   d   D   D U "
   "D     U     D U "
   "D DUD D DUD D DU"
   "D DUD DUD DUD DU"
   "D   D DU  D DU U"
   "B B D  U  D DU U"
   "DUD D DU UD DU U"
   "B U D U B U D U "
   "B   D   B   D   "
   "D D D D D D D D "
   "D D M D         "  
   "D D M D   B D DU"
   "D D M D   d D DU"
   "D DUX D   B D DU"
   "D d D DU UD DUDU"
   "D d D DU UD D DU"  
   " UD D DU UD D DU"
   "DUD DUD DUD DUD "
   "D   D   D       "
   "D   D D D   D D "  
   "D   D D D D D D "
   "    D       D   "
   "    D     D     "
   "D   D  UD D  UDU"  
   "D DUD D  UD D DU"
   "D   D   D D D D "  
   "  D D D D D D DU"
   "D   D U   U D U "  
   "  U D U   U D U "
   "D D D D D D D D "
   "D D D D D D D D "
   "D D M   D D M   "
   "D   M U D   M U "
   "D DUX D  UB D DU"  
   "D DUX D X D  UDU"  
   "D DUX D  UB D DU"  
   "D DUX D  UB D DU"
   "XXD M D D   D DU"  
   "DUDUX D   B D XX"
   "D DUDUD DUD DUDU"
   "D   D DUDU UD DU"  
   "D   D DUDU UD DU"  
   "D   D DUDU UD DU"  
   "D DU UD DU UDUDU"
   "D   D DUDU UD DU"
   "D   M     U M U "
   "D D D D D D D DU"
   "B B D DU UB DU U"
   "B B D DU UD D DU"
   "B   D   B   D   "  
   "B   D   B U D U "
   "D B D DU UD D DU"
   "D  U UD   D  UD "
   "D   D   DU U U U"
   "D   D   D U D U "
   "D   D U   U D   "  
   "  U D   D   D U "
   "D DUD DUDU UD DU"
   "D DUDUD DUDUD DU"
   "B   D     U D U "
   "D   D U D   D U "  
   "  U   U D   D U "
   "D D D DUD D D DU"
   "B       D U D U "
   "D   D   D  UD D "
   "D   X U D U X U "
   "D   D DU UD DUDU"
   "B B D   B B D   "
   "D d D DU UD D DU"
   "D   X U   U X U "
   "BUDUDUDUDUDUDUDU"
   "D U D U D   D U "  
   "D U D   D U DM  "
   "d   D     U D U "
   "D DUD DU UD DUDU"
   "D   X U D   X U "  
   "D U D U   U D U "
   "D     U D     U "  
   "D U   U D   D   "
   "D   D U   U D U "  
   "D               "
   "D   D U   U D U "  
   "D               "
   "B   D U X U D U "
   "D     D         "  
   "D   D D         "
   "D   X U   U D U "
   "D d D DUDUD D DU"
   "D   XxxxD   Xxxx"
   "D   XxxxD   Xxxx"  
   "D DUX D     Xxxx"
   "D D   D D D D D "  
   "D D   D D D   D "
   "D   D   D U D   "
   "D   D   D   D   "  
   "D   D   D U D U "
   "D D D D D       "
   "D DUD DUDUDU UDU"
   "D DUD DUD DUD DU"
   "D   D   D   D DU"
   "D   D   DUD D DU"
   "B B D DUDUD D DU"
   "D   D DUDUD D DU"
   "B   D B B   D DU"])

